// ==UserScript==
// @name         Spotify Hidden Releases
// @namespace    https://github.com/karpuzikov/userscripts
// @version      0.3.2
// @description  Finds hidden Spotify releases, checks MusicBrainz linkage, and opens unlinked releases in Harmony.
// @author       karpuzikov
// @match        https://open.spotify.com/artist/*
// @match        https://open.spotify.com/intl-*/artist/*
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_setClipboard
// @connect      musicbrainz.org
// @updateURL    https://raw.githubusercontent.com/karpuzikov/userscripts/main/browser-tools/spotify-hidden-releases/Spotify_Hidden_Releases.user.js
// @downloadURL  https://raw.githubusercontent.com/karpuzikov/userscripts/main/browser-tools/spotify-hidden-releases/Spotify_Hidden_Releases.user.js
// @run-at       document-idle
// ==/UserScript==

(() => {
'use strict';
const V='0.3.2',BTN='kz-shr-btn',MOD='kz-shr-mod',CACHE_MS=12*3600000;
const HARMONY_LOGO_SVG='<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs><linearGradient id="kz-shr-harmony-gradient" x1="-51.64" y1="190.18" x2="287.01" y2="-2.23" gradientUnits="userSpaceOnUse"><stop offset=".29" stop-color="#ffb92c"/><stop offset="1" stop-color="#c45555"/></linearGradient></defs><path fill="#c45555" d="M68.08 122.59c4.17 2.66 9.11 4.23 14.42 4.23 14.82 0 26.84-12.02 26.84-26.84S97.32 73.14 82.5 73.14c-5.35 0-10.31 1.58-14.5 4.28-.31.02-.63.02-.94.02-2.42 0-4.85-.49-6.9-1.86-2.99-1.99-4.29-6.45-4.77-11.01V21.54L7.74 48.87v102.25l47.64 27.34v-43.03c.49-4.57 1.78-9.02 4.77-11.01 2.06-1.37 4.48-1.86 6.9-1.86.34 0 .68 0 1.02.03Z"/><path fill="url(#kz-shr-harmony-gradient)" d="M63.67 175.1v-39.19c.38-3.11 1.04-4.35 1.25-4.68.26-.13.6-.23 1-.29 5.1 2.74 10.78 4.18 16.58 4.18 19.37 0 35.13-15.76 35.13-35.13S101.87 64.86 82.5 64.86c-5.83 0-11.53 1.45-16.64 4.21-.38-.06-.69-.16-.94-.28-.21-.33-.87-1.57-1.25-4.68V24.9L107.08 0l85.18 48.87v102.25L107.08 200l-43.4-24.9Z"/></svg>';
let state=null,lastPath=location.pathname,mbLast=0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const aid=()=>location.pathname.match(/\/artist\/([A-Za-z0-9]{22})/)?.[1]||null;
const album=id=>`https://open.spotify.com/album/${id}`;
const embed=id=>`https://open.spotify.com/embed/album/${id}`;
const harmony=id=>`https://harmony.pulsewidth.org.uk/release?url=${encodeURIComponent(album(id))}&gtin=&region=&deezer=&spotify=&tidal=&qobuz=`;
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
const norm=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function artistName(){return document.querySelector('main h1,h1')?.textContent?.trim()||document.title.replace(/\s*[-|]\s*Spotify\s*$/i,'').trim()}
function albumIds(text){const out=new Set(),re=/(?:spotify:album:|open\.spotify\.com\/(?:intl-[a-z]{2,3}\/)?album\/|\/album\/)([A-Za-z0-9]{22})/gi;let m;while((m=re.exec(String(text||''))))out.add(m[1]);return out}
function gm(url){return new Promise((ok,no)=>GM_xmlhttpRequest({method:'GET',url,timeout:45000,headers:{Accept:'application/json','User-Agent':`Spotify-Hidden-Releases/${V} (https://github.com/karpuzikov/userscripts)`},onload:ok,onerror:()=>no(new Error('Network error')),ontimeout:()=>no(new Error('Timeout'))}))}
async function mb(url){const wait=1050-(Date.now()-mbLast);if(wait>0)await sleep(wait);mbLast=Date.now();while(true){const r=await gm(url);if(r.status===503){const retry=Math.max(5,Number(r.responseHeaders?.match(/retry-after:\s*(\d+)/i)?.[1]||5));await sleep(retry*1000);continue}if(r.status===404)return null;if(r.status<200||r.status>=300)throw new Error(`MusicBrainz HTTP ${r.status}`);try{return JSON.parse(r.responseText||'{}')}catch{throw new Error('Invalid MusicBrainz response')}}}
async function visibleIds(id){const out=albumIds(document.documentElement.innerHTML);for(const p of [`/artist/${id}/discography/all`,`/artist/${id}/discography/album`,`/artist/${id}/discography/single`,`/artist/${id}/discography/compilation`])try{const r=await fetch(p,{credentials:'include',cache:'no-store'});if(r.ok)albumIds(await r.text()).forEach(x=>out.add(x))}catch{}return out}
async function mbArtist(id){for(const u of [`https://open.spotify.com/artist/${id}`,`https://open.spotify.com/artist/${id}/`]){const d=await mb(`https://musicbrainz.org/ws/2/url?resource=${encodeURIComponent(u)}&inc=artist-rels&fmt=json`);const rel=(d?.relations||[]).find(x=>x['target-type']==='artist'&&x.artist?.id);if(rel)return rel.artist}return null}
function relSpotifyIds(rels){const out=new Set;for(const r of rels||[])albumIds(r?.url?.resource||r?.target||'').forEach(x=>out.add(x));return out}
async function mbReleaseLinks(albumId){const d=await mb(`https://musicbrainz.org/ws/2/url?resource=${encodeURIComponent(album(albumId))}&inc=release-rels&fmt=json`),out=new Map;for(const r of d?.relations||[]){if(r?.['target-type']!=='release'||!r.release?.id)continue;out.set(r.release.id,{id:r.release.id,title:r.release.title||r.release.id,disambiguation:r.release.disambiguation||''})}return[...out.values()]}
async function collectMb(id,currentName,setStatus){const artist=await mbArtist(id);const candidates=new Map,historical=[];if(!artist)return{candidates,historical,error:'MusicBrainz artist link not found'};let offset=0;do{setStatus('Reading MusicBrainz release groups...',`${offset} loaded`,20);const d=await mb(`https://musicbrainz.org/ws/2/release-group?artist=${artist.id}&inc=artist-credits+url-rels&limit=100&offset=${offset}&fmt=json`),rows=d?.['release-groups']||[];for(const r of rows){const names=uniq((r['artist-credit']||[]).map(x=>x.name||x.artist?.name));const old=names.filter(n=>norm(n)!==norm(currentName));if(old.length&&r.title)historical.push({title:r.title,names:old});for(const sid of relSpotifyIds(r.relations))candidates.set(sid,{id:sid,title:r.title||'',artist:names.join(', '),sources:['MusicBrainz release-group Spotify URL']})}offset+=rows.length;if(!rows.length||offset>=Number(d?.['release-group-count']||0))break}while(true);
offset=0;do{setStatus('Reading MusicBrainz releases...',`${offset} loaded`,35);const d=await mb(`https://musicbrainz.org/ws/2/release?artist=${artist.id}&inc=artist-credits+url-rels&limit=100&offset=${offset}&fmt=json`),rows=d?.releases||[];for(const r of rows){const names=uniq((r['artist-credit']||[]).map(x=>x.name||x.artist?.name));const old=names.filter(n=>norm(n)!==norm(currentName));if(old.length&&r.title)historical.push({title:r.title,names:old});for(const sid of relSpotifyIds(r.relations)){const prev=candidates.get(sid);const mbRelease={id:r.id,title:r.title||r.id,disambiguation:r.disambiguation||''};const item={id:sid,title:r.title||'',artist:names.join(', '),sources:['MusicBrainz release Spotify URL'],mbLinked:true,mbReleases:[mbRelease]};if(prev){prev.sources=uniq([...prev.sources,...item.sources]);prev.mbLinked=true;prev.mbReleases=[...(prev.mbReleases||[]),mbRelease].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i)}else candidates.set(sid,item)}}offset+=rows.length;if(!rows.length||offset>=Number(d?.['release-count']||0))break}while(true);
return{candidates,historical:dedupeHistory(historical),artist}}
function dedupeHistory(rows){const m=new Map;for(const r of rows){for(const n of r.names||[]){const k=`${norm(r.title)}|${norm(n)}`;if(!m.has(k))m.set(k,{title:r.title,name:n})}}return[...m.values()]}
async function searchSpotifyUi(query){const path=`/search/${encodeURIComponent(query)}/albums`;try{const r=await fetch(path,{credentials:'include',cache:'no-store'});if(r.ok){const found=albumIds(await r.text());if(found.size)return found}}catch{}
return new Promise(resolve=>{const f=document.createElement('iframe');f.src=path;f.setAttribute('aria-hidden','true');f.style.cssText='position:fixed;left:-10000px;top:-10000px;width:1200px;height:800px;opacity:0;pointer-events:none';document.body.appendChild(f);let ticks=0,done=false;const finish=ids=>{if(done)return;done=true;clearInterval(timer);f.remove();resolve(ids)};const timer=setInterval(()=>{ticks++;try{const d=f.contentDocument;if(d){const found=albumIds(d.documentElement?.innerHTML||'');if(found.size&&ticks>=3)return finish(found)}}catch{}if(ticks>=16)finish(new Set)},500);f.onload=()=>{try{const found=albumIds(f.contentDocument?.documentElement?.innerHTML||'');if(found.size)setTimeout(()=>finish(found),1000)}catch{}}})}
async function verify(item){let html='';try{const r=await fetch(embed(item.id),{credentials:'omit',cache:'no-store'});if(r.ok)html=await r.text()}catch{}if(!html)try{const r=await fetch(album(item.id),{credentials:'include',cache:'no-store'});if(r.ok)html=await r.text()}catch{}if(!html)return null;const d=new DOMParser().parseFromString(html,'text/html'),og=p=>d.querySelector(`meta[property="${p}"]`)?.content?.trim()||'',desc=og('og:description');item.title||=og('og:title').replace(/\s*[-|]\s*Spotify\s*$/i,'').trim();item.image||=og('og:image');item.artist||=desc.match(/^(.+?)\s*[·•-]\s*(?:Album|EP|Single)\b/i)?.[1]?.trim()||'';return item}
function status(a,b='',p=0){const m=modal();m.querySelector('#kz-s').textContent=a;m.querySelector('#kz-d').textContent=b;m.querySelector('#kz-p').style.width=`${Math.max(0,Math.min(100,p))}%`}
async function discover(){const id=aid(),name=artistName(),visible=await visibleIds(id),errors=[];status('Resolving artist in MusicBrainz...',name,10);let md;try{md=await collectMb(id,name,status)}catch(e){md={candidates:new Map,historical:[]};errors.push(e.message)}if(md.error)errors.push(md.error);const candidates=md.candidates;
const searches=md.historical.slice(0,40);let i=0;for(const h of searches){i++;status('Searching Spotify with historical artist credits...',`${i}/${searches.length}: ${h.title} - ${h.name}`,50+Math.round(i/Math.max(1,searches.length)*25));try{const found=await searchSpotifyUi(`${h.title} ${h.name}`);for(const sid of found){if(visible.has(sid))continue;const prev=candidates.get(sid);if(prev)prev.sources=uniq([...prev.sources,`Spotify search: ${h.name}`]);else candidates.set(sid,{id:sid,title:'',artist:'',sources:[`Spotify search: ${h.name}`]})}}catch(e){errors.push(`Spotify search: ${e.message}`)}}
for(const sid of GM_getValue(`kz-shr-manual:${id}`,[])||[]){const prev=candidates.get(sid)||{id:sid,title:'',artist:'',sources:[]};prev.sources=uniq([...prev.sources,'Manual']);prev.manual=true;candidates.set(sid,prev)}
const hidden=[...candidates.values()].filter(x=>!visible.has(x.id)||x.manual),results=[];let n=0;for(const item of hidden){n++;status('Verifying hidden Spotify pages...',`${n}/${hidden.length}`,76+Math.round(n/Math.max(1,hidden.length)*12));const v=await verify(item);if(!v)continue;if(v.mbLinked&&v.mbReleases?.length){v.mbReleases=[...v.mbReleases].filter((x,i,a)=>x?.id&&a.findIndex(y=>y?.id===x.id)===i)}else{status('Checking MusicBrainz links...',`${n}/${hidden.length}: ${v.title||v.id}`,88+Math.round(n/Math.max(1,hidden.length)*11));try{v.mbReleases=await mbReleaseLinks(v.id);v.mbLinked=v.mbReleases.length>0}catch(e){v.mbReleases=[];v.mbLinked=false;v.mbCheckError=e.message;errors.push(`MusicBrainz ${v.id}: ${e.message}`)}}results.push(v)}results.sort((a,b)=>(a.title||'').localeCompare(b.title||''));return{results,errors:uniq(errors),stats:{visible:visible.size,candidates:candidates.size,mb:candidates.size,searches:searches.length,linked:results.filter(x=>x.mbLinked).length,unlinked:results.filter(x=>!x.mbLinked).length}}}
function css(){if(document.getElementById('kz-shr-css'))return;const s=document.createElement('style');s.id='kz-shr-css';s.textContent=`#${BTN}{border:0;border-radius:999px;background:#1ed760;color:#000;font:700 14px Arial;padding:11px 18px;margin-left:12px;cursor:pointer}#${MOD}{position:fixed;inset:0;z-index:2147483646;background:#000b;display:grid;place-items:center;padding:20px;color:#fff;font:13px Arial}#${MOD}[hidden]{display:none}.p{width:min(1050px,96vw);max-height:92vh;background:#121212;border:1px solid #333;border-radius:14px;overflow:hidden;display:flex;flex-direction:column}.h,.t,.s{padding:14px 18px;border-bottom:1px solid #292929}.h{display:flex;align-items:center;gap:10px}.h b{font-size:21px}.h span{color:#999;margin-right:auto}.b{border:1px solid #444;border-radius:999px;background:#252525;color:#fff;padding:9px 13px;font-weight:700;cursor:pointer;text-decoration:none}.t{display:grid;grid-template-columns:1fr auto 1.4fr auto;gap:9px}.i{background:#202020;color:#fff;border:1px solid #444;border-radius:8px;padding:10px}.s small{color:#aaa}.bar{height:4px;background:#292929;margin-top:9px}.bar i{display:block;height:100%;background:#1ed760;width:0}.note{padding:10px 18px;color:#aaa;border-bottom:1px solid #292929}.list{overflow:auto;padding:12px 18px 18px;display:grid;gap:9px}.card{display:grid;grid-template-columns:64px 1fr auto;gap:12px;align-items:center;background:#191919;border:1px solid #2e2e2e;border-radius:10px;padding:10px}.cover{width:64px;height:64px;object-fit:cover;border-radius:6px;background:#292929}.title{font-size:15px;font-weight:800}.meta{color:#aaa;margin-top:4px}.badges{display:flex;flex-wrap:wrap;gap:5px;margin-top:6px}.badge{background:#303030;border-radius:999px;padding:3px 7px;font-size:11px}.mb-ok{background:#153d24;color:#9ee6ad}.mb-no{background:#4a2424;color:#ffb1b1}.mbicon,.harmony{display:inline-flex;align-items:center;justify-content:center;width:30px;height:30px;border-radius:7px;background:#252525;border:1px solid #444;vertical-align:middle}.mbicon img{width:20px;height:20px}.harmony svg{width:22px;height:22px;display:block}.err{padding:8px 18px;color:#ffb0b0}.empty{padding:35px;text-align:center;color:#aaa}`;document.head.appendChild(s)}
function modal(){css();let m=document.getElementById(MOD);if(m)return m;m=document.createElement('div');m.id=MOD;m.hidden=true;m.innerHTML=`<div class="p"><div class="h"><b>Spotify Hidden Releases</b><span>v${V} - Under construction</span><button id="kz-r" class="b">Rescan</button><button id="kz-x" class="b">X</button></div><div class="t"><input id="kz-f" class="i" placeholder="Filter"><select id="kz-mf" class="i"><option value="all">MusicBrainz: All</option><option value="linked">Linked to MusicBrainz</option><option value="unlinked">Not linked to MusicBrainz</option></select><input id="kz-m" class="i" placeholder="Known hidden Spotify album URL or ID"><button id="kz-a" class="b">Save hidden ID</button></div><div class="s"><b id="kz-s">Ready.</b><br><small id="kz-d"></small><div class="bar"><i id="kz-p"></i></div></div><div class="note">Each release is checked against MusicBrainz. Linked releases open directly in MusicBrainz; unlinked releases get a Harmony lookup button.</div><div id="kz-e"></div><div id="kz-l" class="list"></div></div>`;document.body.appendChild(m);m.querySelector('#kz-x').onclick=()=>m.hidden=true;m.querySelector('#kz-r').onclick=()=>scan(true);m.querySelector('#kz-f').oninput=render;m.querySelector('#kz-mf').onchange=render;m.querySelector('#kz-a').onclick=saveManual;return m}
function render(){const m=modal(),l=m.querySelector('#kz-l'),q=norm(m.querySelector('#kz-f').value),mf=m.querySelector('#kz-mf')?.value||'all';if(!state){l.innerHTML='<div class="empty">Run a scan.</div>';return}m.querySelector('#kz-e').innerHTML=state.errors?.length?`<div class="err">Partial scan: ${esc(state.errors.join('; '))}</div>`:'';const r=state.results.filter(x=>(!q||norm(`${x.title} ${x.artist} ${x.id} ${(x.sources||[]).join(' ')}`).includes(q))&&(mf==='all'||(mf==='linked'&&x.mbLinked)||(mf==='unlinked'&&!x.mbLinked)));l.innerHTML=r.length?r.map(x=>{const mb=(x.mbReleases||[]).map(rel=>`<a class="mbicon" target="_blank" rel="noopener noreferrer" href="https://musicbrainz.org/release/${rel.id}" title="${esc(rel.disambiguation?`MusicBrainz: ${rel.title} (${rel.disambiguation})`:`MusicBrainz: ${rel.title}`)}"><img src="https://musicbrainz.org/favicon.ico" alt="MusicBrainz"></a>`).join('');const hy=!x.mbLinked?`<a class="harmony" target="_blank" rel="noopener noreferrer" href="${harmony(x.id)}" title="Search this Spotify release in Harmony">${HARMONY_LOGO_SVG}</a>`:'';return`<div class="card">${x.image?`<img class="cover" src="${esc(x.image)}">`:'<div class="cover"></div>'}<div><div class="title">${esc(x.title||x.id)}</div><div class="meta">${esc(x.artist||'')} - ${x.id}</div><div class="badges"><span class="badge">Hidden from visible discography</span><span class="badge ${x.mbLinked?'mb-ok':'mb-no'}">${x.mbLinked?`MusicBrainz linked${x.mbReleases.length>1?` (${x.mbReleases.length})`:''}`:'Not linked to MusicBrainz'}</span>${(x.sources||[]).slice(0,6).map(s=>`<span class="badge">${esc(s)}</span>`).join('')}</div></div><div>${mb}${hy} <a class="b" target="_blank" rel="noopener noreferrer" href="${album(x.id)}">Open</a> <a class="b" target="_blank" rel="noopener noreferrer" href="${embed(x.id)}">Embed</a> <button class="b copy" data-u="${album(x.id)}">Copy</button></div></div>`}).join(''):'<div class="empty">No releases match the current filters.</div>';l.querySelectorAll('.copy').forEach(b=>b.onclick=()=>GM_setClipboard(b.dataset.u,'text'))}
async function scan(force=false){const id=aid();if(!id)return;const m=modal();m.hidden=false;const ck=GM_getValue(`kz-shr-cache-v32:${id}`,null);if(!force&&ck?.time&&Date.now()-ck.time<CACHE_MS){state=ck.state;status(`Loaded ${state.results.length} cached hidden releases.`,'Use Rescan for fresh data.',100);render();return}try{state=await discover();GM_setValue(`kz-shr-cache-v32:${id}`,{time:Date.now(),state});status(`Found ${state.results.length} hidden releases.`,`${state.stats.linked||0} linked to MusicBrainz; ${state.stats.unlinked||0} not linked; ${state.stats.candidates} candidates checked.`,100);render()}catch(e){status('Scan failed.',e.message,100)}}
async function saveManual(){const id=aid(),inp=modal().querySelector('#kz-m'),x=String(inp.value||'').match(/(?:album\/)?([A-Za-z0-9]{22})(?:[/?#]|$)/)?.[1];if(!id||!x)return status('Invalid Spotify album URL or ID.','',100);GM_setValue(`kz-shr-manual:${id}`,uniq([...(GM_getValue(`kz-shr-manual:${id}`,[])||[]),x]));inp.value='';const v=await verify({id:x,sources:['Manual'],manual:true});if(!v)return status('Could not verify Spotify album.',x,100);try{v.mbReleases=await mbReleaseLinks(v.id);v.mbLinked=v.mbReleases.length>0}catch{v.mbReleases=[];v.mbLinked=false}if(!state)state={results:[],errors:[],stats:{candidates:0,visible:0,searches:0,linked:0,unlinked:0}};state.results=state.results.filter(y=>y.id!==x);state.results.push(v);render();status('Saved hidden release.',v.title||x,100)}
function inject(){if(lastPath!==location.pathname){lastPath=location.pathname;state=null}const id=aid();if(!id){document.getElementById(BTN)?.remove();return}if(document.getElementById(BTN))return;css();const b=document.createElement('button');b.id=BTN;b.textContent='Show hidden releases';b.onclick=e=>{e.preventDefault();e.stopPropagation();scan(false)};(document.querySelector('main h1,h1')?.parentElement||document.querySelector('main')||document.body).appendChild(b)}
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});setInterval(inject,1200);inject();
})();
